
services:
  database:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: baselibros
    volumes:
      - ./mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -proot || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "3307:3306"  
    networks:
      - mi_red

  backend:
    build:
      context: /libros_spring
      dockerfile: Dockerfile
    container_name: springboot_container
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/baselibros  
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8080:8080"
    depends_on:
      database:
        condition: service_healthy
    networks:
      - mi_red

  frontend:
    image: nginx:latest
    container_name: angular_container
    ports:
      - "4200:80"
    volumes:
      - ./angular-app:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - mi_red


  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jenkins
    restart: always
    ports:
      - "9090:8080"
      - "50000:50000"
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      -  bookbase_jenkins_home:/var/jenkins_home 
    networks:
      - mi_red


networks:
  mi_red:
    driver: bridge

volumes:
  bookbase_jenkins_home: